title: Martin Kellogg

baseurl: "/martinjkellogg.com/"
url: "https://kelloggm.github.io/"

collections:
  bib:
    output: true
  grants:
    output: true

# show things with future dates
future: true

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
