title: Martin Kellogg

baseurl: "/~mjk76/"
url: "https://web.njit.edu"

collections:
  bib:
    output: true
  grants:
    output: true

# show things with future dates
future: true

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
