title: Martin Kellogg

baseurl: "/~kelloggm/"
url: "https://homes.cs.washington.edu/"

collections:
  bib:
    output: true

# show things with future dates
future: true

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
